/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Agent topology graph. Defines which agents participate and how they communicate.
 */
export interface AgentGraph {
  nodes: {
    /**
     * Unique agent identifier
     */
    agent_id: string;
    /**
     * Agent role in topology
     */
    role: "supervisor" | "worker" | "verifier" | "planner" | "specialist";
    /**
     * Reference to ModelBinding in RunPlan.model_bindings
     */
    model_binding_ref: string;
    budget_ceiling: {
      token_limit: string;
      usd_micros: string;
      [k: string]: unknown;
    };
    status: "pending" | "running" | "completed" | "failed" | "cancelled";
    /**
     * Parent agent for subagent delegation
     */
    parent_agent_id?: string | null;
    /**
     * 0 for root agent, decremented for children
     */
    delegation_depth?: number;
    /**
     * References to ToolGrant IDs in RunPlan.tool_grants
     */
    tool_grant_refs?: string[];
    skill_binding_refs?: string[];
  }[];
  edges: {
    from_agent: string;
    to_agent: string;
    /**
     * dependency=wait for, communication=send message, delegation=parent-child, result_handoff=artifact transfer
     */
    edge_type: "dependency" | "communication" | "delegation" | "result_handoff";
    /**
     * What artifact types flow on this edge
     */
    artifact_types?: string[];
  }[];
}
