/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Parent sends this to Authorization Service. Authorization Service signs, NOT parent.
 */
export interface ChildCapabilityRequest {
  child_manifest_hash: string;
  parent_delegation_proof: string;
  budget_ceiling: {
    [k: string]: unknown;
  };
  tool_grants: unknown[];
  resource_grants: unknown[];
  delegation_depth: number;
}
