/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dynamic risk features. Replaces static tool risk classification.
 */
export interface EffectRisk {
  locality: "local" | "remote" | "external";
  operation: "read" | "create" | "write" | "delete" | "execute" | "publish" | "communicate" | "purchase";
  reversibility: "guaranteed" | "best_effort" | "none";
  data_egress: "none" | "metadata" | "content" | "sensitive";
  network_access: boolean;
  credential_access: boolean;
  blast_radius: "single_resource" | "bounded_set" | "workspace" | "organization" | "public" | "unbounded";
  /**
   * Decimal string, e.g. '5000000' for $5.00
   */
  financial_impact_usd_micros: string;
  human_impact: "none" | "self" | "internal_people" | "external_people" | "public";
  external_visibility: "private" | "shared" | "public";
  regulatory_sensitivity: string[];
}
