/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Dynamic risk features. Replaces static tool risk classification.
 */
export interface EffectRisk {
  locality: "local" | "remote" | "external";
  operation: "read" | "create" | "write" | "delete" | "execute" | "publish" | "communicate" | "purchase";
  reversibility: "guaranteed" | "best_effort" | "none";
 data_egress: "none" | "metadata" | "content" | "sensitive";
 network_access: boolean;
 /**
  * Authoritative network policy (FG3). Replaces boolean network_access as the enforcement target.
  */
 egress_policy?: {
   mode?: "disabled" | "allowlist" | "denylist" | "open";
   domain_rules?: {
     action: "allow" | "deny";
     host: string;
   }[];
   unix_sockets?: "denied" | "allowlist";
   allow_local_binding?: boolean;
   socks5?: boolean;
 };
 /**
  * Screen/desktop operation risk dimensions (FG1 Computer Use). Absent = no screen access.
  */
 screen_access?: {
   surface?: "none" | "browser" | "native_app" | "desktop" | "fullscreen";
   input_modes?: ("screenshot" | "click" | "type" | "key" | "clipboard")[];
   app_scope?: "per_app_approved" | "workspace" | "system";
 };
 credential_access: boolean;
  blast_radius: "single_resource" | "bounded_set" | "workspace" | "organization" | "public" | "unbounded";
  /**
   * Decimal string, e.g. '5000000' for $5.00
   */
  financial_impact_usd_micros: string;
  human_impact: "none" | "self" | "internal_people" | "external_people" | "public";
  external_visibility: "private" | "shared" | "public";
  regulatory_sensitivity: string[];
}
