/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StreamEvent {
  event_id: string;
  sequence: number;
  run_id: string;
  agent_id?: string | null;
  step_id?: string | null;
  type: string;
  timestamp: string;
  payload: {
    [k: string]: unknown;
  };
  redaction_applied: boolean;
}
