/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EvidencePackage {
  requirement_id: string;
  commit_sha: string;
  source_files: unknown[];
  tests_added: unknown[];
  commands_run: unknown[];
  exit_codes: number[];
  test_results: {
    [k: string]: unknown;
  };
  coverage: {
    [k: string]: unknown;
  };
  security_checks: {
    [k: string]: unknown;
  };
  verifier_result: "pass" | "fail";
  verifier_model?: string;
}
