/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human-signed production release authorization. No AI agent may approve its own release.
 */
export interface ReleaseApproval {
  release_id: string;
  build_digest: string;
  release_manifest_hash: string;
  target_environment: "production";
  /**
   * Authorized human principal
   */
  approved_by: string;
  approved_at: string;
  /**
   * Approval TTL, e.g., 24h
   */
  expires_at: string;
  /**
   * Unforgeable human signature
   */
  webauthn_signature: string;
}
