/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SkillSpec {
  name: string;
  /**
   * Compact catalog text returned by skill_search before full instructions are loaded
   */
  summary: string;
  tags: string[];
  version: string;
  /**
   * Content-addressed instructions loaded only after Router selects this skill
   */
  instructions_ref: string;
  precedence_scope: "builtin" | "global" | "project" | "enterprise";
  supported_experience_profiles: unknown[];
  input_schema_ref: string;
  output_schema_ref: string;
  required_context: unknown[];
  required_tools: unknown[];
  allowed_effect_classes: unknown[];
  workflow_template_ref: string;
  verification_template_ref: string;
  failure_policy: {
    [k: string]: unknown;
  };
  risk_ceiling: string;
  eval_suite_ref: string;
}
