/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SkillSpec {
  name: string;
  version: string;
  supported_experience_profiles: unknown[];
  input_schema_ref: string;
  output_schema_ref: string;
  required_context: unknown[];
  required_tools: unknown[];
  allowed_effect_classes: unknown[];
  workflow_template_ref: string;
  verification_template_ref: string;
  failure_policy: {
    [k: string]: unknown;
  };
  risk_ceiling: string;
  eval_suite_ref: string;
}
