/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Machine-readable tool specification. Replaces minimal v8 ToolDefinition.
 */
export interface ToolSpec {
  name: string;
  version: string;
  domains: string[];
  implementation_status:
    "interface_only" | "stub" | "mock" | "partial" | "implemented" | "verified" | "production_certified";
  input_schema_ref: string;
  output_schema_ref: string;
  effect_model: {
    [k: string]: unknown;
  };
  risk_feature_extractor: string;
  preconditions: {
    [k: string]: unknown;
  }[];
  postconditions: {
    [k: string]: unknown;
  }[];
  timeout_policy: {
    [k: string]: unknown;
  };
  cancellation_policy: {
    [k: string]: unknown;
  };
  retry_policy: {
    [k: string]: unknown;
  };
  idempotency_policy: {
    [k: string]: unknown;
  };
  sandbox_policy: {
    [k: string]: unknown;
  };
  network_policy: {
    [k: string]: unknown;
  };
  credential_requirements: {
    [k: string]: unknown;
  }[];
  data_egress_policy: {
    [k: string]: unknown;
  };
  receipt_schema_ref: string;
  verification_adapter: string;
  reconciliation_adapter?: string | null;
  compensation_adapter?: string | null;
  unit_tests?: string[];
  integration_tests?: string[];
  adversarial_tests?: string[];
  maturity: "draft" | "mock" | "sandbox_verified" | "provider_sandbox_verified" | "production_certified";
}
