/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Workflow step DAG. Defines execution order and dependencies.
 */
export interface WorkflowGraph {
  nodes: {
    step_id: string;
    step_type:
      | "model_call"
      | "tool_call"
      | "verification"
      | "decision"
      | "parallel_fork"
      | "parallel_join"
      | "human_input"
      | "compensation";
    status: "pending" | "dispatched" | "executing" | "verifying" | "done" | "failed" | "blocked" | "skipped";
    /**
     * Which agent executes this step
     */
    agent_id_ref?: string | null;
    /**
     * For tool_call steps
     */
    tool_name?: string | null;
    retry_count?: number;
    /**
     * Agent can tune during implementation
     */
    max_retries?: number;
    /**
     * Agent can tune during implementation
     */
    timeout_ms?: number;
  }[];
  edges: {
    from_step: string;
    to_step: string;
    /**
     * Optional condition expression for conditional edges (e.g., 'result.success == true')
     */
    condition?: string | null;
  }[];
}
