import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ToolExecutor } from '../../tools/tool-executor.js';
import { AuthorizationService } from '../../security/authorization-service.js';
import { InMemoryCapabilityStateStore } from '../../security/capability.js';
import { PolicyEnforcementPoint } from '../../security/pep.js';
import { generateKeyPairSync } from 'node:crypto';
import { ToolRegistry } from '../../tools/tool-registry.js';
import { VirtualFilesystem, LocalBackend } from '../../vfs/virtual-filesystem.js';
import { PolicyEngine, type Policy } from '../../security/policy-engine.js';
import { DurableSession } from '../../session/durable-session.js';
import { readFile } from '../../tools/read-file.js';
import type { ToolSpec } from '../../../spec/types/tool-spec.js';

function toolSpec(name: string): ToolSpec {
  return { name, version: '1.0.0', domains: ['coding'], implementation_status: 'implemented', input_schema_ref: 'in.json', output_schema_ref: 'out.json', effect_model: {}, risk_feature_extractor: 'ex', preconditions: [], postconditions: [], timeout_policy: {}, cancellation_policy: {}, retry_policy: {}, idempotency_policy: {}, sandbox_policy: {}, network_policy: {}, credential_requirements: [], data_egress_policy: {}, receipt_schema_ref: 'r.json', verification_adapter: 'v', maturity: 'draft' } as ToolSpec;
}

describe('ToolExecutor unified pipeline', () => {
  let tmp: string, vfs: VirtualFilesystem, executor: ToolExecutor;
  let tr: ToolRegistry, snap: ReturnType<ToolRegistry['freezeSnapshot']>, pe: PolicyEngine, session: DurableSession;
  let fixedNow: string, stateStore: InMemoryCapabilityStateStore, authz: AuthorizationService, pep: PolicyEnforcementPoint;
  beforeEach(() => {
    tmp = mkdtempSync(join(tmpdir(), 'tex-'));
    tr = new ToolRegistry();
    tr.register(toolSpec('read_file'));
    tr.register(toolSpec('write_file'));
    snap = tr.freezeSnapshot();
    vfs = new VirtualFilesystem([{ prefix: '/workspace', read: true, write: true }]);
    vfs.mount(new LocalBackend('/workspace', tmp));
    pe = new PolicyEngine({ version: 'v1', default_decision: 'deny', allowed_tools: ['read_file'], allowed_resource_prefixes: ['/workspace'], rules: [{ id: 'allow-read', priority: 1, effect: 'allow', tools: ['read_file'], resource_prefixes: ['/workspace'] }] } as Policy);
    session = new DurableSession('s1');
    session.acquireWriter();
    // Inject deps from composition root (not self-generated by ToolExecutor)
    fixedNow = '2026-01-01T00:00:00.000Z';
    const { privateKey, publicKey } = generateKeyPairSync('ed25519');
    stateStore = new InMemoryCapabilityStateStore();
    const consumedTokens = new Set<string>();
    authz = new AuthorizationService({ private_key: privateKey, public_key: publicKey, state_store: stateStore, now: () => fixedNow });
    pep = new PolicyEnforcementPoint({
      policy_engine: pe,
      capability_authority: {
        verify_signature: async (token) => { try { const r = await stateStore.read(token.token_id); return !!r; } catch { return false; } },
        consume: async (tokenId) => { if (consumedTokens.has(tokenId)) return false; consumedTokens.add(tokenId); return true; },
      },
      audit_sink: { write: async () => {} },
      now: () => fixedNow,
    });
    executor = new ToolExecutor({ toolRegistry: tr, snapshot: snap, vfs, policyEngine: pe, session }, { authz, pep, stateStore, now: () => fixedNow });
  });
  afterEach(() => rmSync(tmp, { recursive: true, force: true }));

  it('executes through the pipeline: snapshot check → policy → session audit → receipt', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f.txt' });
    });
    
    expect(receipt.tool_name).toBe('read_file');
    expect(receipt.success).toBe(true);
    expect(receipt.input_hash).toMatch(/^[0-9a-f]{16}$/);
  });

  it('rejects tool not in frozen snapshot', async () => {
    await expect(executor.execute('evil_tool', {}, async () => 'x')).rejects.toThrow();
  });

  it('rejects tool not in policy allowed list', async () => {
    await expect(executor.execute('write_file', {}, async () => 'x')).rejects.toThrow(/policy denied/);
  });

  it('records tool_call and tool_result in session event log', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'data');
    await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/f.txt' }));
    const events = executor['deps'].session.getEvents();
    expect(events.some(e => e.type === 'tool_call')).toBe(true);
    expect(events.some(e => e.type === 'tool_result')).toBe(true);
  });


  it('receipt contains token_id, policy_decision, input_hash, output_hash', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f.txt' });
    });
    expect(receipt.token_id).toBeDefined();
    expect(receipt.policy_decision).toBe('allow');
    expect(receipt.input_hash).toMatch(/^[0-9a-f]{16}$/);
    expect(receipt.output_hash).toMatch(/^[0-9a-f]{16}$/);
    expect(receipt.duration_ms).toBeGreaterThanOrEqual(0);
    expect(receipt.success).toBe(true);
  });

  it('receipt has timestamp in ISO format', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f.txt' });
    });
    expect(receipt.timestamp).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it('session records tool_call event with token_id', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f.txt' });
    });
    const events = session.getEvents();
    const toolCallEvent = events.find(e => e.type === 'tool_call');
    expect(toolCallEvent).toBeDefined();
    expect((toolCallEvent!.data as { token_id: string }).token_id).toBeDefined();
  });

  it('session records tool_result event with receipt', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    await executor.execute('read_file', { path: '/workspace/f.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f.txt' });
    });
    const events = session.getEvents();
    const toolResultEvent = events.find(e => e.type === 'tool_result');
    expect(toolResultEvent).toBeDefined();
    expect((toolResultEvent!.data as { receipt: { tool_name: string } }).receipt.tool_name).toBe('read_file');
  });

  it('tool execution error records error event and throws', async () => {
    await expect(executor.execute('read_file', { path: '/workspace/nonexistent' }, async () => {
      throw new Error('file not found');
    })).rejects.toThrow();
    const events = session.getEvents();
    expect(events.some(e => e.type === 'error')).toBe(true);
  });

  it('receipt success is false on tool error', async () => {
    try {
      await executor.execute('read_file', { path: '/workspace/nonexistent' }, async () => {
        throw new Error('file not found');
      });
    } catch { /* expected */ }
    const events = session.getEvents();
    const errorEvent = events.find(e => e.type === 'error');
    expect(errorEvent).toBeDefined();
  });

  it('tool with effect_model uses risk from ToolSpec not name-based', async () => {
    // Register a tool with specific effect_model
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'read', tags: ['fs'], transport: 'native', risk_ceiling: 'low', operation: 'read', locality: 'local', network_access: false, credential_access: false },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = '2026-01-01T00:00:00.000Z';
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const executor2 = new ToolExecutor(
      { toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session },
      { authz: az2, pep: pp2, stateStore: ss2, now: () => fn },
    );
    writeFileSync(join(tmp, 'f2.txt'), 'content');
    const { receipt } = await executor2.execute('read_file', { path: '/workspace/f2.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/f2.txt' });
    });
    expect(receipt.success).toBe(true);
  });

  it('execute throws ToolExecutorError for unknown tool', async () => {
    await expect(executor.execute('unknown_tool', {}, async () => 'x')).rejects.toThrow();
  });

  it('execute throws ToolExecutorError when policy denies', async () => {
    await expect(executor.execute('write_file', { path: '/workspace/x' }, async () => 'x')).rejects.toThrow(/policy denied/);
  });

  it('execute throws when policy evaluation denies (risk tier exceeded)', async () => {
    // write_file is not in allowed_tools, so policy denies
    await expect(executor.execute('write_file', { path: '/workspace/x' }, async () => 'x')).rejects.toThrow();
  });

  it('execute throws when capability issue fails', async () => {
    // Use a policy engine that denies all tools via explicit deny rule
    const pe2 = new PolicyEngine({ version: 'v2', default_decision: 'deny', allowed_tools: ['read_file'], allowed_resource_prefixes: ['/denied'], rules: [{ id: 'deny-all', priority: 1, effect: 'deny', tools: ['*'], resource_prefixes: ['/denied'] }] } as Policy);
    const tr2 = new ToolRegistry();
    tr2.register(toolSpec('read_file'));
    const snap2 = tr2.freezeSnapshot();
    const fn = '2026-01-01T00:00:00.000Z';
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe2, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const executor2 = new ToolExecutor(
      { toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe2, session },
      { authz: az2, pep: pp2, stateStore: ss2, now: () => fn },
    );
    await expect(executor2.execute('read_file', { path: '/denied/x' }, async () => 'x')).rejects.toThrow();
  });

  it('multiple sequential executions each produce separate receipts', async () => {
    writeFileSync(join(tmp, 'a.txt'), 'a');
    writeFileSync(join(tmp, 'b.txt'), 'b');
    const { receipt: r1 } = await executor.execute('read_file', { path: '/workspace/a.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/a.txt' });
    });
    const { receipt: r2 } = await executor.execute('read_file', { path: '/workspace/b.txt' }, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/b.txt' });
    });
    expect(r1.token_id).not.toBe(r2.token_id);
    expect(r1.success).toBe(true);
    expect(r2.success).toBe(true);
  });

  it('execute with complex nested input preserves hash', async () => {
    writeFileSync(join(tmp, 'nested.txt'), 'data');
    const complexInput = { path: '/workspace/nested.txt', metadata: { nested: { deep: { value: 42 } } } };
    const { receipt } = await executor.execute('read_file', complexInput, async (deps) => {
      return readFile(deps.vfs, { path: '/workspace/nested.txt' });
    });
    expect(receipt.input_hash).toMatch(/^[0-9a-f]{16}$/);
    expect(receipt.success).toBe(true);
  });



  it('PEP deny when verify_signature returns false', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({
      policy_engine: pe,
      capability_authority: { verify_signature: async () => false, consume: async () => true },
      audit_sink: { write: async () => {} },
      now: () => fn,
    });
    const exec2 = new ToolExecutor(
      { toolRegistry: tr, snapshot: snap, vfs, policyEngine: pe, session },
      { authz: az2, pep: pp2, stateStore: ss2, now: () => fn },
    );
    await expect(exec2.execute('read_file', { path: '/workspace/f.txt' }, async () => 'x')).rejects.toThrow();
  });

  it('PEP deny when consume returns false (token already used)', async () => {
    writeFileSync(join(tmp, 'f.txt'), 'hello');
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({
      policy_engine: pe,
      capability_authority: { verify_signature: async () => true, consume: async () => false },
      audit_sink: { write: async () => {} },
      now: () => fn,
    });
    const exec2 = new ToolExecutor(
      { toolRegistry: tr, snapshot: snap, vfs, policyEngine: pe, session },
      { authz: az2, pep: pp2, stateStore: ss2, now: () => fn },
    );
    await expect(exec2.execute('read_file', { path: '/workspace/f.txt' }, async () => 'x')).rejects.toThrow();
  });

  it('tool with write effect_model executes successfully', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'read', tags: [], transport: 'native', operation: 'write', locality: 'local', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'wf.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/wf.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/wf.txt' }));
    expect(receipt.success).toBe(true);
  });

  it('tool with execute effect_model and network_access executes', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'exec', tags: [], transport: 'native', operation: 'execute', locality: 'remote', reversibility: 'none', data_egress: 'metadata', network_access: false, credential_access: true, blast_radius: 'workspace', financial_impact_usd_micros: '1000', human_impact: 'self', external_visibility: 'shared', regulatory_sensitivity: ['gdpr'] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'ef.txt'), 'exec');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/ef.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/ef.txt' }));
    expect(receipt.success).toBe(true);
  });

  it('tool with root argument extracts resource id', async () => {
    writeFileSync(join(tmp, 'rf.txt'), 'root');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/rf.txt', root: '/workspace' }, async (deps) => readFile(deps.vfs, { path: '/workspace/rf.txt' }));
    expect(receipt.success).toBe(true);
  });

  it('tool with sources array extracts resource ids', async () => {
    writeFileSync(join(tmp, 'sf.txt'), 'sources');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/sf.txt', sources: ['/workspace/a', '/workspace/b'] }, async (deps) => readFile(deps.vfs, { path: '/workspace/sf.txt' }));
    expect(receipt.success).toBe(true);
  });

  it('callCount increments after each execution', async () => {
    writeFileSync(join(tmp, 'c1.txt'), 'a');
    writeFileSync(join(tmp, 'c2.txt'), 'b');
    await executor.execute('read_file', { path: '/workspace/c1.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/c1.txt' }));
    await executor.execute('read_file', { path: '/workspace/c2.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/c2.txt' }));
    // If callCount didn't increment, the second execution might use the same operation_id
    // Both should succeed
    const events = session.getEvents();
    expect(events.filter(e => e.type === 'tool_call').length).toBeGreaterThanOrEqual(2);
  });

  it('receipt error is set on tool execution failure', async () => {
    try {
      await executor.execute('read_file', { path: '/workspace/nonexistent' }, async () => { throw new Error('not found'); });
    } catch { /* expected */ }
    const events = session.getEvents();
    const errorEvent = events.find(e => e.type === 'error');
    expect(errorEvent).toBeDefined();
    expect((errorEvent!.data as { error: string }).error).toBe('not found');
  });

  it('execute with empty input object works', async () => {
    writeFileSync(join(tmp, 'empty.txt'), 'empty');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/empty.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/empty.txt' }));
    expect(receipt.success).toBe(true);
    expect(receipt.input_hash).toMatch(/^[0-9a-f]{16}$/);
  });

  it('execute output_hash is set on success', async () => {
    writeFileSync(join(tmp, 'oh.txt'), 'output');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/oh.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/oh.txt' }));
    expect(receipt.output_hash).toBeDefined();
    expect(receipt.output_hash).toMatch(/^[0-9a-f]{16}$/);
  });

  it('receipt tool_name matches executed tool', async () => {
    writeFileSync(join(tmp, 'tn.txt'), 'name');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/tn.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tn.txt' }));
    expect(receipt.tool_name).toBe('read_file');
  });

  it('execute with null input throws ToolExecutorError', async () => {
    await expect(executor.execute('read_file', null, async () => 'x')).rejects.toThrow();
  });



  it('receipt derived_risk_tier is 0 for default read-only local tool', async () => {
    writeFileSync(join(tmp, 'tier0.txt'), 'data');
    const { receipt } = await executor.execute('read_file', { path: '/workspace/tier0.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier0.txt' }));
    expect(receipt.derived_risk_tier).toBe(0);
  });

  it('receipt derived_risk_tier is 3 for write operation tool', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'write', tags: [], transport: 'native', operation: 'write', locality: 'local', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'tier2.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/tier2.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier2.txt' }));
    expect(receipt.derived_risk_tier).toBe(3);
  });

  it('receipt derived_risk_tier is 4 for execute operation tool', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'exec', tags: [], transport: 'native', operation: 'execute', locality: 'local', reversibility: 'none', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'tier_exec.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/tier_exec.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier_exec.txt' }));
    expect(receipt.derived_risk_tier).toBe(4);
  });

  it('receipt derived_risk_tier is 1 for remote locality tool', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'remote', tags: [], transport: 'native', operation: 'read', locality: 'remote', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'tier_remote.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/tier_remote.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier_remote.txt' }));
    expect(receipt.derived_risk_tier).toBe(1);
  });

  it('receipt derived_risk_tier reflects credential_access', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'cred', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: true, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'tier_cred.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/tier_cred.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier_cred.txt' }));
    expect(receipt.derived_risk_tier).toBe(2);
  });

  it('receipt derived_risk_tier reflects data_egress', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'egress', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'content', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'tier_egress.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/tier_egress.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/tier_egress.txt' }));
    expect(receipt.derived_risk_tier).toBe(2);
  });



  it('capability issue fails when AuthorizationService max_ttl is too short', async () => {
    writeFileSync(join(tmp, 'ttl.txt'), 'data');
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn, max_ttl_ms: 1000 });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr, snapshot: snap, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    await expect(exec2.execute('read_file', { path: '/workspace/ttl.txt' }, async () => 'x')).rejects.toThrow(/capability issue failed/);
    const events = session.getEvents();
    expect(events.some(e => e.type === 'error' && (e.data as { reason: string }).reason.includes('capability issue failed'))).toBe(true);
  });

  it('tool with delete effect_model has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'delete', tags: [], transport: 'native', operation: 'delete', locality: 'local', reversibility: 'none', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'del.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/del.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/del.txt' }));
    expect(receipt.derived_risk_tier).toBe(5); // delete (+3) + none (+2) = 5
  });

  it('tool with external locality has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'external', tags: [], transport: 'native', operation: 'read', locality: 'external', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'ext.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/ext.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/ext.txt' }));
    expect(receipt.derived_risk_tier).toBe(2); // external (+2)
  });

  it('tool with unbounded blast_radius has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'unbounded', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'unbounded', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'unb.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/unb.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/unb.txt' }));
    expect(receipt.derived_risk_tier).toBe(4); // unbounded (+4)
  });

  it('tool with public external_visibility has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'public', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'public', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'pub.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/pub.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/pub.txt' }));
    expect(receipt.derived_risk_tier).toBe(2); // public visibility (+2)
  });

  it('tool with regulatory_sensitivity has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'regulated', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: ['gdpr'] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'reg.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/reg.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/reg.txt' }));
    expect(receipt.derived_risk_tier).toBe(1); // regulatory_sensitivity (+1)
  });

  it('tool with financial_impact has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'costly', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '10000', human_impact: 'none', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'fin.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/fin.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/fin.txt' }));
    expect(receipt.derived_risk_tier).toBe(1); // financial_impact >= 10000 (+1)
  });

  it('tool with human_impact self has correct tier', async () => {
    const tr2 = new ToolRegistry();
    tr2.register({
      ...toolSpec('read_file'),
      effect_model: { summary: 'human', tags: [], transport: 'native', operation: 'read', locality: 'local', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource', financial_impact_usd_micros: '0', human_impact: 'self', external_visibility: 'private', regulatory_sensitivity: [] },
    } as ToolSpec);
    const snap2 = tr2.freezeSnapshot();
    const fn = fixedNow;
    const { privateKey: pk2, publicKey: pub2 } = generateKeyPairSync('ed25519');
    const ss2 = new InMemoryCapabilityStateStore();
    const az2 = new AuthorizationService({ private_key: pk2, public_key: pub2, state_store: ss2, now: () => fn });
    const pp2 = new PolicyEnforcementPoint({ policy_engine: pe, capability_authority: { verify_signature: async () => true, consume: async () => true }, audit_sink: { write: async () => {} }, now: () => fn });
    const exec2 = new ToolExecutor({ toolRegistry: tr2, snapshot: snap2, vfs, policyEngine: pe, session }, { authz: az2, pep: pp2, stateStore: ss2, now: () => fn });
    writeFileSync(join(tmp, 'hum.txt'), 'data');
    const { receipt } = await exec2.execute('read_file', { path: '/workspace/hum.txt' }, async (deps) => readFile(deps.vfs, { path: '/workspace/hum.txt' }));
    expect(receipt.derived_risk_tier).toBe(1); // human_impact self (+1)
  });

});
