import type { SkillSpec } from "./skill-registry.js";
/**
 * Phase 1 base skill definitions (declarative data, not mutated by Stryker).
 */
// ---------------------------------------------------------------------------
// Phase 1 base skills
// ---------------------------------------------------------------------------

export function createBaseSkills(): SkillSpec[] {
  return [
    {
      name: 'repository_exploration',
      summary: 'Explore a code repository structure and identify key files',
      tags: ['coding', 'exploration', 'repository'],
      version: '1.0.0',
      instructions_ref: 'skills/repository-exploration.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/repo-explore-input.json',
      output_schema_ref: 'schemas/repo-explore-output.json',
      required_context: ['repository_path'],
      required_tools: ['list_directory', 'read_file', 'search_files'],
      allowed_effect_classes: ['read_only'],
      workflow_template_ref: 'workflows/explore.md',
      verification_template_ref: 'verify/explore.md',
      failure_policy: { on_failure: 'abort', max_retries: 0 },
      risk_ceiling: 'tier_1',
      eval_suite_ref: 'evals/repo-explore.json',
    },
    {
      name: 'bug_fix',
      summary: 'Identify and fix a seeded bug in a codebase',
      tags: ['coding', 'bugfix', 'development'],
      version: '1.0.0',
      instructions_ref: 'skills/bug-fix.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/bug-fix-input.json',
      output_schema_ref: 'schemas/bug-fix-output.json',
      required_context: ['repository_path', 'bug_description'],
     required_tools: ['read_file', 'edit_file', 'search_files', 'execute_command'],
      allowed_effect_classes: ['non_idempotent_write'],
     workflow_template_ref: 'workflows/bugfix.md',
      verification_template_ref: 'verify/bugfix.md',
      failure_policy: { on_failure: 'rollback', max_retries: 1 },
      risk_ceiling: 'tier_2',
      eval_suite_ref: 'evals/bug-fix.json',
    },
    {
      name: 'feature_implementation',
      summary: 'Implement a new feature based on a specification',
      tags: ['coding', 'feature', 'development'],
      version: '1.0.0',
      instructions_ref: 'skills/feature-impl.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/feature-input.json',
      output_schema_ref: 'schemas/feature-output.json',
      required_context: ['repository_path', 'feature_spec'],
      required_tools: ['read_file', 'write_file', 'edit_file', 'search_files', 'execute_command'],
      allowed_effect_classes: ['non_idempotent_write'],
      workflow_template_ref: 'workflows/feature.md',
      verification_template_ref: 'verify/feature.md',
      failure_policy: { on_failure: 'rollback', max_retries: 0 },
      risk_ceiling: 'tier_3',
      eval_suite_ref: 'evals/feature.json',
    },
    {
      name: 'test_and_verify',
      summary: 'Run tests and verify code correctness',
      tags: ['coding', 'testing', 'verification'],
      version: '1.0.0',
      instructions_ref: 'skills/test-verify.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/test-input.json',
      output_schema_ref: 'schemas/test-output.json',
      required_context: ['repository_path'],
      required_tools: ['execute_command', 'read_file'],
      allowed_effect_classes: ['read_only'],
      workflow_template_ref: 'workflows/test.md',
      verification_template_ref: 'verify/test.md',
      failure_policy: { on_failure: 'report', max_retries: 1 },
      risk_ceiling: 'tier_1',
      eval_suite_ref: 'evals/test.json',
    },
    {
      name: 'research_with_citations',
      summary: 'Research a topic from local sources and report with citations',
      tags: ['research', 'citations', 'analysis'],
      version: '1.0.0',
      instructions_ref: 'skills/research.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/research-input.json',
      output_schema_ref: 'schemas/research-output.json',
      required_context: ['source_set', 'research_question'],
      required_tools: ['read_file', 'search_files', 'parse_document'],
      allowed_effect_classes: ['read_only'],
      workflow_template_ref: 'workflows/research.md',
      verification_template_ref: 'verify/research.md',
      failure_policy: { on_failure: 'partial_report', max_retries: 0 },
      risk_ceiling: 'tier_1',
      eval_suite_ref: 'evals/research.json',
    },
    {
      name: 'document_summary',
      summary: 'Parse and summarize a document with page-level citations',
      tags: ['documents', 'summary', 'parsing'],
      version: '1.0.0',
      instructions_ref: 'skills/doc-summary.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/doc-input.json',
      output_schema_ref: 'schemas/doc-output.json',
      required_context: ['document_path'],
      required_tools: ['parse_document', 'read_file'],
      allowed_effect_classes: ['read_only'],
      workflow_template_ref: 'workflows/summary.md',
      verification_template_ref: 'verify/summary.md',
      failure_policy: { on_failure: 'abort', max_retries: 0 },
      risk_ceiling: 'tier_1',
      eval_suite_ref: 'evals/doc-summary.json',
    },
    {
      name: 'writing_refinement',
      summary: 'Turn a brief into a polished draft with rubric self-check',
      tags: ['writing', 'drafting', 'editing'],
      version: '1.0.0',
      instructions_ref: 'skills/writing.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/writing-input.json',
      output_schema_ref: 'schemas/writing-output.json',
      required_context: ['brief', 'style_guide'],
      required_tools: ['create_artifact', 'write_file'],
      allowed_effect_classes: ['idempotent_write'],
      workflow_template_ref: 'workflows/writing.md',
      verification_template_ref: 'verify/writing.md',
      failure_policy: { on_failure: 'revise', max_retries: 2 },
      risk_ceiling: 'tier_2',
      eval_suite_ref: 'evals/writing.json',
    },
    {
      name: 'dependency_aware_planning',
      summary: 'Construct a dependency-valid plan and reject cyclic dependencies',
      tags: ['planning', 'dependencies', 'scheduling'],
      version: '1.0.0',
      instructions_ref: 'skills/planning.md',
      precedence_scope: 'builtin',
      supported_experience_profiles: ['all'],
      input_schema_ref: 'schemas/planning-input.json',
      output_schema_ref: 'schemas/planning-output.json',
      required_context: ['goal', 'constraints'],
      required_tools: ['create_artifact'],
      allowed_effect_classes: ['pure'],
      workflow_template_ref: 'workflows/planning.md',
      verification_template_ref: 'verify/planning.md',
      failure_policy: { on_failure: 'replan', max_retries: 1 },
      risk_ceiling: 'tier_1',
      eval_suite_ref: 'evals/planning.json',
    },
  ];
}
