/**
 * Phase 3 tool definitions (AH-TOOL-VIDEO-GEN-001, AH-TOOL-MUSIC-GEN-001,
 * AH-TOOL-VIDEO-EDIT-001, AH-TOOL-BROWSER-001, AH-TOOL-COMPUTER-001).
 *
 * Declarative ToolSpecs only — the executable handlers live in their own
 * modules (generate-video.ts / generate-music.ts / edit-video.ts /
 * browser-operate.ts / computer-operate.ts). Registered separately from
 * createPhase1ToolDefinitions so Phase 1's exact-definition tests are
 * untouched.
 */
import type { ToolSpec } from '../contracts/index.js';

export function createPhase3ToolDefinitions(): ToolSpec[] {
  return [
    {
      name: 'video_gen',
      version: '1.0.0',
      domains: ['media', 'content_creation'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/generate-video-input.json',
      output_schema_ref: 'schemas/generate-video-output.json',
      effect_model: {
        transport: 'http_api',
        tool_group: 'media_gen',
        risk: 'T3',
        locality: 'remote',
        operation: 'create',
        reversibility: 'best_effort',
        data_egress: 'content',
        network_access: true,
        credential_access: true,
        blast_radius: 'single_resource',
        human_impact: 'none',
        external_visibility: 'private',
        financial_impact_usd_micros: '0',
        regulatory_sensitivity: [],
      },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 300_000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: true },
      run_phase_binding: ['agent'],
      credential_requirements: [{ name: 'video_gen_api_key', scope: 'video:generate' }],
      data_egress_policy: { egress: 'content' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
    },
    {
      name: 'music_gen',
      version: '1.0.0',
      domains: ['media', 'content_creation'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/generate-music-input.json',
      output_schema_ref: 'schemas/generate-music-output.json',
      effect_model: {
        transport: 'http_api',
        tool_group: 'media_gen',
        risk: 'T2',
        locality: 'remote',
        operation: 'create',
        reversibility: 'best_effort',
        data_egress: 'content',
        network_access: true,
        credential_access: true,
        blast_radius: 'single_resource',
        human_impact: 'none',
        external_visibility: 'private',
        financial_impact_usd_micros: '0',
        regulatory_sensitivity: [],
      },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 300_000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: true },
      run_phase_binding: ['agent'],
      credential_requirements: [{ name: 'music_gen_api_key', scope: 'music:generate' }],
      data_egress_policy: { egress: 'content' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
    },
    {
      name: 'video_edit',
      version: '1.0.0',
      domains: ['media', 'content_creation'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/edit-video-input.json',
      output_schema_ref: 'schemas/edit-video-output.json',
      effect_model: {
        transport: 'cli_wrapper',
        tool_group: 'media_edit',
        cli_toolchain_ref: 'ffmpeg',
        risk: 'T2',
        locality: 'local',
        operation: 'create',
        reversibility: 'none',
        data_egress: 'none',
        network_access: false,
        credential_access: false,
        blast_radius: 'workspace',
        human_impact: 'none',
        external_visibility: 'private',
        financial_impact_usd_micros: '0',
        regulatory_sensitivity: [],
      },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 600_000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: true },
      network_policy: { network_required: false },
      run_phase_binding: ['agent'],
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
    },
    {
      name: 'browser_operate',
      version: '1.0.0',
      domains: ['research', 'web'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/browser-operate-input.json',
      output_schema_ref: 'schemas/browser-operate-output.json',
      effect_model: {
        transport: 'wrapper',
        tool_group: 'web_automation',
        risk: 'T3',
        locality: 'remote',
        operation: 'execute',
        reversibility: 'none',
        data_egress: 'content',
        network_access: true,
        credential_access: false,
        blast_radius: 'bounded_set',
        human_impact: 'none',
        external_visibility: 'shared',
        financial_impact_usd_micros: '0',
        regulatory_sensitivity: [],
      },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 60_000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: true },
      run_phase_binding: ['agent'],
      credential_requirements: [],
      data_egress_policy: { egress: 'content' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      display_policy: {
        surface_scope: 'browser_only',
        screenshot_isolation: 'exclude_self_output',
        global_interrupt_consumed: true,
        single_session_lock: true,
      },
      maturity: 'sandbox_verified',
    },
    {
      name: 'computer_operate',
      version: '1.0.0',
      domains: ['desktop', 'automation'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/computer-operate-input.json',
      output_schema_ref: 'schemas/computer-operate-output.json',
      effect_model: {
        transport: 'wrapper',
        tool_group: 'desktop_automation',
        locality: 'local',
        operation: 'execute',
        reversibility: 'none',
        data_egress: 'none',
        network_access: false,
        credential_access: false,
        blast_radius: 'bounded_set',
        human_impact: 'self',
        external_visibility: 'private',
        financial_impact_usd_micros: '0',
        regulatory_sensitivity: [],
      },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 60_000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      run_phase_binding: ['agent'],
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      display_policy: {
        surface_scope: 'desktop',
        screenshot_isolation: 'exclude_self_output',
        global_interrupt_consumed: true,
        single_session_lock: true,
      },
      maturity: 'sandbox_verified',
    },
  ];
}

export const PHASE3_TOOL_NAMES = [
  'video_gen',
  'music_gen',
  'video_edit',
  'browser_operate',
  'computer_operate',
] as const;
