/**
 * AH-TOOL-REGISTRY-001: Tool Definitions
 *
 * Phase 1 tool definitions for the 9 local tools. Each definition maps
 * to a ToolSpec in the registry. This file provides the canonical
 * source for tool metadata that the registry validates and stores.
 *
 * Tool definitions are declarative data, not executable code.
 */
import type { ToolSpec } from '../contracts/index.js';

export function createPhase1ToolDefinitions(): ToolSpec[] {
  return [
    {
      name: 'read_file',
      version: '1.0.0',
      domains: ['coding', 'documents', 'research'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/read-file-input.json',
      output_schema_ref: 'schemas/read-file-output.json',
      effect_model: { locality: 'local', operation: 'read', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'write_file',
      version: '1.0.0',
      domains: ['coding', 'writing'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/write-file-input.json',
      output_schema_ref: 'schemas/write-file-output.json',
      effect_model: { locality: 'local', operation: 'write', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'edit_file',
      version: '1.0.0',
      domains: ['coding'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/edit-file-input.json',
      output_schema_ref: 'schemas/edit-file-output.json',
      effect_model: { locality: 'local', operation: 'write', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'list_directory',
      version: '1.0.0',
      domains: ['coding', 'documents', 'research'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/list-dir-input.json',
      output_schema_ref: 'schemas/list-dir-output.json',
      effect_model: { locality: 'local', operation: 'read', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'search_files',
      version: '1.0.0',
      domains: ['coding', 'documents', 'research'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/search-input.json',
      output_schema_ref: 'schemas/search-output.json',
      effect_model: { locality: 'local', operation: 'read', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'bounded_set' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 10000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'execute_command',
      version: '1.0.0',
      domains: ['coding'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/exec-input.json',
      output_schema_ref: 'schemas/exec-output.json',
      effect_model: { locality: 'local', operation: 'execute', reversibility: 'none', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'workspace' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 30000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: true },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'create_artifact',
      version: '1.0.0',
      domains: ['writing', 'planning'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/artifact-input.json',
      output_schema_ref: 'schemas/artifact-output.json',
      effect_model: { locality: 'local', operation: 'create', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'ask_user',
      version: '1.0.0',
      domains: ['personal_assistant', 'coding', 'writing'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/ask-user-input.json',
      output_schema_ref: 'schemas/ask-user-output.json',
      effect_model: { locality: 'local', operation: 'communicate', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'self' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 60000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'parse_document',
      version: '1.0.0',
      domains: ['documents', 'research'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/parse-doc-input.json',
      output_schema_ref: 'schemas/parse-doc-output.json',
      effect_model: { locality: 'local', operation: 'read', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 10000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'apply_patch',
      version: '1.0.0',
      domains: ['coding'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/apply-patch-input.json',
      output_schema_ref: 'schemas/apply-patch-output.json',
      effect_model: { locality: 'local', operation: 'write', reversibility: 'best_effort', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'bounded_set' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 10000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: false },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'undo',
      version: '1.0.0',
      domains: ['coding'],
      implementation_status: 'production_certified',
      input_schema_ref: 'schemas/undo-input.json',
      output_schema_ref: 'schemas/undo-output.json',
      effect_model: { locality: 'local', operation: 'write', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'workspace' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 5000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'production_certified',
    },
    {
      name: 'web_fetch',
      version: '1.0.0',
      domains: ['research', 'coding'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/web-fetch-input.json',
      output_schema_ref: 'schemas/web-fetch-output.json',
      effect_model: { locality: 'remote', operation: 'read', reversibility: 'guaranteed', data_egress: 'metadata', network_access: true, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 30000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 2 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: true },
      credential_requirements: [],
      data_egress_policy: { egress: 'metadata' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
    },
    {
      name: 'web_search',
      version: '1.0.0',
      domains: ['research', 'coding'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/web-search-input.json',
      output_schema_ref: 'schemas/web-search-output.json',
      effect_model: { locality: 'remote', operation: 'read', reversibility: 'guaranteed', data_egress: 'metadata', network_access: true, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 30000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 2 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: true },
      credential_requirements: [],
      data_egress_policy: { egress: 'metadata' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
    },
    {
      name: 'screenshot',
      version: '1.0.0',
      domains: ['coding', 'documents', 'research'],
      implementation_status: 'implemented',
      input_schema_ref: 'schemas/screenshot-input.json',
      output_schema_ref: 'schemas/screenshot-output.json',
      effect_model: { locality: 'local', operation: 'read', reversibility: 'guaranteed', data_egress: 'none', network_access: false, credential_access: false, blast_radius: 'single_resource' },
      risk_feature_extractor: 'default',
      preconditions: [],
      postconditions: [],
      timeout_policy: { timeout_ms: 10000 },
      cancellation_policy: { cancellable: true },
      retry_policy: { max_retries: 0 },
      idempotency_policy: { idempotent: true },
      sandbox_policy: { sandbox: false },
      network_policy: { network_required: false },
      credential_requirements: [],
      data_egress_policy: { egress: 'none' },
      receipt_schema_ref: 'schemas/receipt.json',
      verification_adapter: 'read_back',
      maturity: 'sandbox_verified',
      display_policy: { surface_scope: 'desktop', screenshot_isolation: 'exclude_self_output' },
    },
  ];
}

export const PHASE1_TOOL_NAMES = [
  'read_file', 'write_file', 'edit_file', 'list_directory',
  'search_files', 'execute_command', 'apply_patch', 'undo', 'create_artifact', 'ask_user',
  'parse_document', 'web_fetch', 'web_search', 'screenshot',
] as const;
